-- Initial SQL Tables and sample questions/answers

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `qbcoref`
--

-- --------------------------------------------------------

--
-- Table structure for table `answers`
--

CREATE TABLE IF NOT EXISTS `answers` (
  `aid` int(11) NOT NULL AUTO_INCREMENT,
  `qid` int(11) NOT NULL,
  `answer` text NOT NULL,
  PRIMARY KEY (`aid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=101 ;

--
-- Dumping data for table `answers`
--

INSERT INTO `answers` (`aid`, `qid`, `answer`) VALUES
(1, 1, 'Much Ado About Nothing\n'),
(2, 2, 'Japan \n'),
(3, 3, 'William Wordsworth\n'),
(4, 4, 'War and Peace \n'),
(5, 5, 'Geoffrey Chaucer\n'),
(6, 6, 'David Malouf\n'),
(7, 7, 'Stephan Mallarm\n'),
(8, 8, 'The Piazza Tales\n'),
(9, 9, 'The Count of Monte Cristo or Le Comte de Monte Cristo\n'),
(10, 10, 'Lines composed a few miles above Tintern Abbey on revisiting the banks of the Wye during a tour\n'),
(11, 11, 'Twelfth Night\n'),
(12, 12, 'Victor Hugos Preface to Cromwell \n'),
(13, 13, 'Frankenstein, or the Modern Prometheus\n'),
(14, 14, 'Schindler''s Ark \n'),
(15, 15, 'John Yossarian \n'),
(16, 16, 'angels\n'),
(17, 17, 'Gravity''s Rainbow\n'),
(18, 18, 'Emily Dickinson\n'),
(19, 19, 'Horace \n'),
(20, 20, 'Emily Dickinson\n'),
(21, 21, 'Hlldor Laxness\n'),
(22, 22, 'logic minimization \n'),
(23, 23, '"Notes Toward a Supreme Fiction"\n'),
(24, 24, 'Richard Wright\n'),
(25, 25, 'Saul Bellow\n'),
(26, 26, 'Luigi Pirandello\n'),
(27, 27, 'The Hunting of the Snark\n'),
(28, 28, 'Stephen Crane\n'),
(29, 29, 'Japan \n'),
(30, 30, 'Leo Nikolayevich Tolstoy\n'),
(31, 31, 'Emily Dickinson\n'),
(32, 32, 'Kenzaburo Oe\n'),
(33, 33, 'Samson and Delilah \n'),
(34, 34, 'Romeo and Juliet\n'),
(35, 35, 'A Tale of Two Cities\n'),
(36, 36, 'Alfred Tennyson, 1st Baron Tennyson\n'),
(37, 37, 'Peer Gynt\n'),
(38, 38, 'The Tin Drum \n'),
(39, 39, 'Arthur Asher Miller\n'),
(40, 40, 'Mr. Biswas or Mohun Biswas\n'),
(41, 41, 'John Maxwell Coetzee\n'),
(42, 42, 'Richard Wright\n'),
(43, 43, 'Quo Vadis\n'),
(44, 44, 'A Streetcar Named Desire\n'),
(45, 45, 'Archibald MacLeish\n'),
(46, 46, 'Brave New World\n'),
(47, 47, 'Nikolai Gogol\n'),
(48, 48, 'The Naked and the Dead\n'),
(49, 49, 'James Joyce\n'),
(50, 50, 'Ali Baba and the 40 Thieves\n'),
(51, 51, 'Oscar Wilde\n'),
(52, 52, 'The Autocrat of the Breakfast Table\n'),
(53, 53, 'Madame Bovary\n'),
(54, 54, 'Talcott Parsons\n'),
(55, 55, 'ode\n'),
(56, 56, 'Luigi Pirandello\n'),
(57, 57, 'The Imaginary Invalid or The Hypochondriac \n'),
(58, 58, 'One Hundred Years of Solitude \n'),
(59, 59, 'Walker Percy\n'),
(60, 60, 'The Poor Christ of Bomba or Le Pauvre Christ de Bomba\n'),
(61, 61, 'Karamazov Family \n'),
(62, 62, 'John Milton\n'),
(63, 63, 'Jean-Paul Charles Aymard Sartre\n'),
(64, 64, 'Eudora Welty\n'),
(65, 65, 'The Rubaiyat of Omar Khayyam\n'),
(66, 66, 'Lois Lowry \n'),
(67, 67, 'Ernst Theodor Amadeus Hoffman\n'),
(68, 68, 'Jim\n'),
(69, 69, 'The Bronze Horseman: A Petersburg Tale \n'),
(70, 70, 'Charles Baudelaire\n'),
(71, 71, 'Stendhal \n'),
(72, 72, 'Henry Valentine Miller\n'),
(73, 73, 'Brighton Rock\n'),
(74, 74, 'Phyllis Wheatley\n'),
(75, 75, 'John Updike\n'),
(76, 76, 'Sarah Orne Jewett\n'),
(77, 77, 'The Preface to the Lyrical Ballads \n'),
(78, 78, 'James I \n'),
(79, 79, 'John dos Passos\n'),
(80, 80, 'Ben Jonson\n'),
(81, 81, 'The Alexandria Quartet\n'),
(82, 82, 'The Story of the Stone \n'),
(83, 83, 'Mahmoud Darwish\n'),
(84, 84, 'Thanatopsis\n'),
(85, 85, 'Sister Carrie\n'),
(86, 86, 'Li Po \n'),
(87, 87, 'Seven Gothic Tales \n'),
(88, 88, 'Samuel Richardson\n'),
(89, 89, 'Argentina\n'),
(90, 90, 'Aeschylus\n'),
(91, 91, 'St. Augustine of Hippo \n'),
(92, 92, 'The Leopard \n'),
(93, 93, 'Notre-Dame de Paris \n'),
(94, 94, 'Ode on the Death of a Favorite Cat, Drowned in a Tub of Gold Fishes\n'),
(95, 95, 'The Sorrows of Young Werther\n'),
(96, 96, 'Charles Mingus\n'),
(97, 97, 'Toni Morrison \n'),
(98, 98, 'Rosencrantz and Guildenstern \n'),
(99, 99, 'Arrow of God\n'),
(100, 100, 'Charles Kingsley\n');

-- --------------------------------------------------------

--
-- Table structure for table `coreferences`
--

CREATE TABLE IF NOT EXISTS `coreferences` (
  `cid` int(11) NOT NULL AUTO_INCREMENT,
  `qid` int(11) NOT NULL,
  `pos_start` int(11) NOT NULL,
  `pos_end` int(11) NOT NULL,
  `description` text NOT NULL,
  `coref_group` int(11) NOT NULL,
  `author` varchar(255) NOT NULL,
  `date_added` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `questions`
--

CREATE TABLE IF NOT EXISTS `questions` (
  `qid` int(11) NOT NULL AUTO_INCREMENT,
  `question` text NOT NULL,
  PRIMARY KEY (`qid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=101 ;

--
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`qid`, `question`) VALUES
(1, 'One character in this work remarks that comparisons are odorous, and one scene involves Margaret dressing up as one of the protagonists and pretending to be Borachio''s lover, a deception that is believed by Don Pedro but revealed by Friar Francis. This subplot may have been inspired by the works of Matteo Bandello and is the result of machinations by Don John to trick Claudio into thinking that Hero is unfaithful to him. Better known is its account of a kind of merry war between two characters who can''t decide whether they want to get married. For 10 points, name this Shakespearean comedy about Beatrice and Benedick.\n'),
(2, 'One author from this country describes a man who sells his family''s land to The Emperor in The Silent Cry. In addition to Oe, a poet from this country wrote about the sea at Sado and a frog jumping into a pond. In addition to the author of Narrow Road to the Deep North, another author from this country described Lady Aoi''s relationship with the title prince in The Tale of Genji. For 10 points, name this homeland of Basho and Lady Murasaki.\n'),
(3, 'This poet wrote a long autobiographical poem involving an ascent of Mount Snowdon, as well as a poem asserting "the child is father of the man." His poems "Strange fits of passion have I known" and "A slumber did my spirit seal" were dedicated to Lucy. This author of (*) "Ode: Intimations of Immortality" wrote a poem inspired by a "host of golden daffodils," "I Wandered Lonely as a Cloud," and co-wrote Lyrical Ballads along with Samuel Taylor Coleridge. For 10 points, name this English Romantic poet of "The Prelude" and "Tintern Abbey."\n'),
(4, 'In this work, a stout woman nicknamed The Terrible Dragon berates a female protagonist for failing to kill herself with arsenic, and a purplish dog named Gray howls next to a birch tree after an unseen shot kills Platon. One character uses numerology to prove he must kill the Antichrist. One scene in this work impersonally describes a moon cut out of cardboard on an opera set which (*) Anatole and his sister Hlne watch. Its narration is often interrupted by its authors deterministic theory of history. At its end, Princess Marya weds the soldier Nikolai, whose sister is Natasha Rostov. For 10 points, name this work featuring Pierre Bezukhov and Napoleons invasion of Russia, by Leo Tolstoy.\n'),
(5, 'One of his works opens with the god of love talking to a daisy queen. That work includes Cleopatra and Medea and is entitled The Legend of Good Women. Another of his works represents John of Gaunt as a man in black and is entitled The Book of the Duchess, while another work is about birds meeting on Valentine''s Day, The Parlement of Fowls. His most famous work involves a woman who tells about a knight learning what women want, The Wife of Bath, who is staying at the Tabard Inn. For 10 points, name this poet of the Canterbury Tales.\n'),
(6, 'This author described each rifleshot hammerstroke as another notch in the silence in the title poem of his most recent poetry collection, Typewriter Music. He wrote about Jim Saddler, who sees his friend Clancy killed during World War I, in the novel Fly Away Peter. He created Digger Keen and Vic Curran, who were both imprisoned by the Japanese during World War II, in his novel The Great World. In his most famous novel, the lives of Lachlan Beattie and his cousins Janet and Meg are affected when the McIvor family takes in Gemmy Fairley, an Englishman who is stranded in Australia. For 10 points, name this Australian author of Remembering Babylon.\n'),
(7, 'One of his poems finds master ici-bas and its curse makes the speaker stop up with the foul vomit of Stupidity in the face of a color that names this poet''s lyric work on the sky that features sad chimneys. A work that opens his last collection of poems has a one-word title, simultaneously meaning greetings and bottoms up and uses imagery from the Odyssey, finding a troop/of many Sirens upside down in the speaker''s champagne glass. In another sonnet by this poet of Brise Marin or Sea (*) Breeze, the titular location is compared to a meteorite after the octet describes the career of the titular author and in another of this poet''s works, the title character''s crime ends his passion, compared to bursting pomegranates. In that poem labeled an Eclogue but is simply a monologue, the title character bids farewell to two characters saying he shall see the shades you became. The subtitle of never will abolish fate appears in large, all capital, letters spread through the lines of Un coup de ds or A Throw of the Dice. For 10 points, name this French Symbolist poet who discussed the titular mythical creature encountering two nymphs in his The Afternoon of a Faun.\n'),
(8, 'The story which gives this collection its title features a narrator who encounters a girl named Marianna after climbing a mountain in search of fairies. Its final story tells of an architect named Bannadonna who is killed by a mechanism which he created for the titular bell tower. Another story discusses the two sides of tortoises as well as relating the tale of a stranded Chola widow, Hunilla. That story is a series of ten sketches about the Galapagos Islands, The Encantadas. Also including a story about a slave rebellion on Amasa Delano''s ship and one about a man who likes to say I would prefer not to, for 10 points, name this short story collection including Benito Cereno, Bartleby, the Scrivener, and four other stories by Herman Melville.\n'),
(9, 'In this novel, the Saint-Mrans are the first victims of Hlose''s poisoning rampage. Barrois drinks the bromine meant for Valentine''s paralyzed grandfather. The protagonist saves Valentine after Maximilien confesses his love. The protagonist falls in love with Hayde. The Count of Morcerf, also known as Fernand Mondego, marries Mercds. The protagonist discovers Abb Faria''s fortune and adopts the title alias while seeking revenge for false imprisonment in the Chteau d''If by Villefort. For 10 points, name this novel about Edmond Dants, by Alexander Dumas.\n'),
(10, 'The speaker in this work mentions his dear, dear Sister!, noting that it is her privilege to lead from joy to joy. This had lead to a feminist reading of the work, connecting the author''s identification of nature as female to his deaf sister. The speaker notes let the moon shine on thee in thy solitary walk in this work, which mentions steep woods and lofty cliffs, and this green pastoral landscape towards its end. Inspired after the author went on a trip of Southern England with his friend William Culvert, this work opens with the lines Five years have past; five summers, with the length of five long winters. FTP, identify this poem composed a few miles above a ruined religious structure on the River Wye, a work by William Wordsworth.\n'),
(11, 'One character in this play reads a letter which says Some are born great, some achieve greatness, and some have greatness thrust upon ''em. A note in this play is forged by Maria and asks its recipient to wear yellow stockings and cross garters. In this play, the sea captain Antonio becomes enraged at the supposed theft of his purse and is arrested by the Duke of Ilyria. One of its subplots concerns a duel in which Andrew Aguecheek and Toby Belch are wounded. A group of characters plot against the pompous steward Malvolio in this play, which centers on the courts of the wealthy countess Olivia and Duke Orsino. For 10 points, name this Shakespeare comedy in which the twins Viola and Sebastian are separated after a shipwreck.\n'),
(12, 'At the end of this work, its author notes that he has been reluctant to cite authorities, preferring reasons to them, but nevertheless provides quotes from Aristotle and Boileau to support his position. While this work acknowledges the soundness of the arguments that use the example of the ancients, its author refuses to reply to them, adding that we are constructing no system here we are a historian, not a critic. This work claims that the age of the epic draws near its end, before outlining how Christianity leads poetry to the truth, and argues that the perfect combination of the grotesque and the sublime is to be found in Shakespeare. This work opens by claiming that the drama contained in the following pages has nothing to commend it to the good will of the public, and associates the grotesque with the new form of comedy, which this work claims is what distinguishes romantic from classical literature. For 10 points, identify this 1827 essay, a manifesto of the new French drama by Victor Hugo which was meant to precede Hugos play about a British Lord Protector.\n'),
(13, 'One family in this work flees France after rescuing an "unfortunate Muhammadan" who is arrested for his religion the day his daughter Safie arrives from Constantinople. In addition to the De Laceys, another character in this work educated himself by reading about the Northwest Passage, and begins the novel by writing a series of letters to Margaret. Justine Moritz is falsely accused of the murder of the title character''s brother William in this novel, which causes the title character to travel to England with Clerval to satisfy the demands of the antagonist for a female companion. The protagonist is rescued by Robert Walton in the Arctic and hails from Lake Geneva. For 10 points, identify this novel subtitled The Modern Prometheus, a Mary Shelley work about creating a certain monster.\n'),
(14, 'Friends of this novel''s title character set him up with a nutria farm in Argentina and a cement factory, both of which fail. Its title character receives a gold ring from his workers upon departing Brinnlitz, which was operated by his company Emalia. This novel''s other characters include the mistresses Ingrid and Victoria Klonowska, as well as a character who refuses on principle to have sex with Helen Hirsch. Both that man and the title character are noted as food-loving, lecherous drunkards, although the (*) Plaszw commander Amon Goeth is far less humane. The title object consists of essentially skilled workers that a Sudeten industrialist saved from death in the concentration camps. For 10 points, name this novel by Thomas Keneally, later adapted into a Spielberg movie.\n'),
(15, 'This man falls in love with the maid with lime colored panties and dates Luciana. He returns to work after The Texan''s good-hearted nature scares everyone, and he is irrational according to Sanderson. His boss is Scheisskopf, and he flies to Sweden to escape Cathcart and Korn, thereby leaving Pianosa. For ten points, name this protagonist who cannot evade piloting duty in Joseph Heller''s Catch-22.\n'),
(16, 'Virginia Woolf, in her essay Professions for Women, advocates killing this type of figure in the House, as she argues these beings represent female chastity and virtue. Lilia Herrinton falls in love with an Italian in E.M. Forster''s first novel, partly titled for these beings in a line taken from Pope''s Essay on Criticism. Millenium Approaches and Perestroika are the two parts of a play subtitled A Gay Fantasia on National Themes written by Tony Kushner and named for these beings in America. Alexander Pope writes that fools rush in where, FTP, what beings fear to tread?\n'),
(17, 'The protagonist of this novel falls in love with Katje, whom he saves from an octopus attack. The protagonist of this novel is sent to the Hermann Goering Casino, where he learns about an object with a serial number consisting of five zeroes. In this novel, which begins with the sentence "A screaming comes across the sky," a V-2 (*) rocket hit follows shortly after each of Tyrone Slothrop''s sexual encounters. For 10 points, name this magnum opus of Thomas Pynchon.\n'),
(18, 'This poet warned for none see God and live in a poem comparing poetry to pil[ing] like thunder to its close. The speaker of another of this author''s poems feels Zero at the Bone after encountering a narrow fellow in the grass. This poet of I felt a Funeral, in my Brain and I''m (*) Nobody! Who are you? wrote about a speaker who hears a Blue / uncertain / stumbling buzz before expiring in I heard a fly buzz / when I died. For 10 points, name this female American poet of Because I could not stop for Death\n'),
(19, 'This man told the addressee of one of his works that it was useless to hoard fancy wine because it would only be wasted by his heir after his death. Another of his works describes the addressee as more splendid than crystal and describes an upcoming sacrifice at the Bandusian fountain, and another exhorts a young woman not to consult horoscopes, but to go ahead and strain her wine. He wrote a work addressed to the Pisones that coined such terms as as in painting, so in poetry and even good Homer nods. His use of the lesser Asclepiad metre meant that each line of many of his works contained a choriamb, examples of which are the name Leucono and the phrase carpe diem. For 10 points, name this Roman lyric poet, the author of Ars Poetica and Dulce et decorum est pro patria mori.\n'),
(20, 'This author noted that Not all the vats upon the Rhine yield such an alcohol in a poem about tasting a liquor never brewed. This poet wrote about experiencing a tighter breathing and zero at the bone when encountering a snake in a poem about a narrow fellow in the grass. This author of Im Nobody, Who Are You? wrote about a carriage ride with death in another poem. For 10 points, name this reclusive American poet known as the Belle of Amherst.\n'),
(21, 'One of this author''s novels is about a cottage frequented by such characters as a former manure-spreader who gets drunk four times a year and a former ship pilot named Captain Hogensen. He also wrote a novel about a collector of manuscripts named Arnas Arnaeus which was published in three parts, including The Bright Jewel and Fire in Copenhagen. In addition to The Fish Can Sing and Iceland''s Bell, he wrote a work dealing with the protagonist''s relationship with his daughter Asta after he is freed from his servitude to the Bailiff of Myri. For 10 points, name this Icelandic author of a novel about the sheep farmer Bjartur, Independent People.\n'),
(22, 'This task can be accomplished approximately by a heuristic algorithm published by Robert Brayton and extended to multi-valued systems by Richard Rudell; that tool is Espresso. A deterministic EXPTIME algorithm to solve this problem begins by determining the so-called DC- and ON-covers, then creates the set of so-called prime implicants, and finally eliminates as many of these as possible; that is the Quine-McCluskey algorithm. For simple systems, this job can be done by translating the systems truth table into a square-shaped Gray code, and then grouping minterms, that being the method of Karnaugh maps. FTP, name this process of finding the smallest set of Boolean functions to create a given output, generally done at the start of digital circuit design to create circuits requiring the least number of gates.\n'),
(23, 'This poem mentions a figure who "needs nothing but deep space, forgets the golden centre" and "plucks on his strings to pluck abysmal glory" while "serenely gazing at the violet abyss." Another figure in this poem claims "I am the spouse, divested of bright gold,/The spouse beyond emerald or amethyst", to which Ozymandias responds "the bride is never naked." Besides "the angel in his clouds" and Nanzia Nunzio, this poem speaks of "Weather by Frans Hals/Brushed up by brushy winds in brushy clouds" and its second section contrasts "the wild orange trees" which "continued to bloom and to bear/ Long after the planter''s death" with "the great statute of the General Du Puy" which is "rubbish in the end." This poem''s first part demands "Let purple Phoebus lie in umber harvest" instead instructing that "the sun must bear no name... but be in the difficulty of what it is to be." Divided into sections like (*) "It Must Be Abstract" and "It Must Give Pleasure", this poem opens "Begin, ephebe, by perceiving the idea of this invention." Announcing that it is possible to "To find the real,... The fiction of an absolute", for 10 points, name this poem by Wallace Stevens, which aspires for the title concept.\n'),
(24, 'After moving to Paris, this author wrote a novel in which Gilbert Blount is murdered by Cross Damon. This author wrote about a mob that burns Bobo alive after four black children encounter a white woman at a swimming hole in his short story "Big Boy Leaves Home," which appears in his collection Uncle Tom''s Children. He gained renown for a novel about a character defended by the lawyer (*) Boris Max after accidentally strangling Mary Dalton. For 10 points, name this author of Black Boy who wrote about Bigger Thomas in Native Son.\n'),
(25, 'One work by this author includes the political analyst Teddy Regler, who is loved by the dissatisfied Clara Veldt. In addition to A Theft, this author depicted Tommy Wilhelm''s alienation from his father in Seize the Day. In another novel by this author, the title character recounts his marriage to [*] Madeline and writes a number of letters, while the protagonist of another novel is raised by Grandma Lausch. That novel opens with the line I am an American, Chicago born. For 10 points, identify this author of Herzog and The Adventures of Augie March, a Jewish-American winner of the 1976 Nobel Prize in Literature.\n'),
(26, 'This author wrote about the policeman Centuri in his work featuring Fronza and Signora Frola. Another work of this author contains a character who wears scissors on her chain and another character who finds a little girl in a fountain. This author of Right You Are, (If You Think You Are!) and Mixing It Up used the latter play in his work that features Madame Pace, The Mother, The Father, The Stepdaughter, and The Son. For 10 points, name this Italian author who wrote Six Characters in Search of an Author.\n'),
(27, 'A protosurrealist version of this work was recently illustrated by Mahendra Singh. Martin Gardner''s annotation of this work argues that those who think this work nonsense base their judgment on the line Then the bowsprit got mixed with the rudder sometimes. An essay by its most recognized illustrator, Henry Holiday, states that it was published separately from Sylvie and Bruno. Its fifth and eighth sections, The Beaver''s Lesson and The Vanishing, state that the Bellman and his crew pursued [the title character] with forks and hope and charmed it with smiles and soap, and that the title character may or may not be a boojum. Subtitled An Agony in Eight Fits, for 10 points, name this poem that describes with infinite humor, the impossible voyage of an improbable crew to find an inconceivable creature, by Lewis Carroll.\n'),
(28, 'This mans experience covering the Greco-Turkish War formed the basis for his novel Active Service. Another of his novels sees the title character date the bartender Pete, but eventually turn to prostitution. In one of his short stories, Billie the oiler is found dead after trying to swim ashore. This author of Maggie: A Girl of the Streets and The Open (*) Boat is best known for writing about the 304th New York regiment, whose members include Jim Conklin and Henry Fleming. For 10 points, name this American author of The Red Badge of Courage.\n'),
(29, 'One author from this country wrote about a criminal whose climb to heaven is ended when he refuses to let others follow behind him on the title object. This home to the author of "The Spider''s Thread" had an author write about a group of children confined to a plague-stricken village. Another writer from this country wrote a work titled after a mechanical toy about (*) Toru Okada. For 10 points, name this nation home to Nip the Buds, Shoot the Kids and The Wind-Up Bird Chronicle authors Kenzaburo Oe and Haruki Murakami.\n'),
(30, 'A grave that is only six feet long ultimately turns out to answer the title question in this authors short story How Much Land Does a Man Need? A man named Olenin leaves for the Caucasus in his novel The Cossacks. In another work by this author, the title civil servant reflects back on his life after suffering a fatal fall installing curtains in his apartment. This author of The Death of Ivan (*) Ilyich wrote a work in which the lover of Count Vronsky commits suicide on a railway. For 10 points, name this author of Anna Karenina and War and Peace.\n'),
(31, 'Robert Bly wrote a poem about visiting this person''s grave with Robert Francis, a subject also treated by the poet Leo Connellan. Sandra Gilbet wrote poems both about this person''s "bread" and about her "Black Cake Walk." Peter Meinke wrote a poem about this person "In Hell." A poem addressed "To" this figure notes "You who desired so much--in vain to ask-- / Yet fed you hunger like an endless task" and "Achieved that stillness ultimately best" and was written by Hart Crane. Billy Collins wrote a poem entitled "Taking off [This Person]''s Clothes," which ends by noting that "reason is a plank," "hope has feathers," and "life is a loaded gun." For 10 points, identify this poet, whose own works include "I taste a liquor never brewed," "Because I could not stop for death," and "I heard a fly buzz when I died."\n'),
(32, 'This writer depicted a group of samurai battle against an imperial army with aid from the One Who Destroys in his novel, The Game of Contemporaneity. Another of his novels is narrated by a liver cancer patient who recounts Happy Days in the work entitled The Day He Himself Shall Wipe My Tears Way. This writer depicted Harelip''s encounter with an African-American POW in The Catch. The protagonist of another of his works is a teacher named Bird, whose son is born with a brain hernia while another of his works follows brothers Matsu and Takashi. For 10 points, name this Japanese writer of A Personal Matter and The Silent Cry.\n'),
(33, 'This opera''s second act was completed four years before its other acts, and was first performed at the home of this opera''s dedicatee, Pauline Viardot-Garcia. In its first act, the chorus''s religious faith is mocked in the aria "Ce Dieu que votre voix implore" after this opera''s lead tenor attempts to rouse the chorus in the arias "Las-tu donc oublie" and "Arretez o mes freres." In the first scene of its third act, that tenor laments his condition in the aria "Vois ma misre, hlas!" This opera''s three main mezzo-soprano arias, including Amour, viens aider ma faiblesse and "Printemps qui commence," are sung to tempt the male lead, who finally capitulates after hearing the aria "Mon cur s''ouvre  ta voix." In this opera''s final scene, priests dance a celebratory bacchanale in the Temple of Dagon before the first title character pulls it down over their heads. For 10 points, name this opera by Camille Saint-Saens about a judge of Israel who loses his strength because of his relationship with the title woman.\n'),
(34, 'One character in this work bemoans these strange flies, these fashion-mongers, these perdona- mi''s. When that character dies, another exclaims fire-eyed fury be my conduct now. Balthasar unwittingly provided that character with false information, causing him to purchase poison from an apothecary. In act one, a character delivers a speech about Queen Mab on the way to a ball. The title character''s refusal to duel the prince of cats, Tybalt, leads to Mercutio''s death. For 10 points, name this Shakespeare play which ends with the suicide of the title "star-crossed lovers."\n'),
(35, 'A retelling of this work from the point of view of one of the main characters was recently written by Susanne Alleyn and is titled A Far Better Rest. In the preface the reader learns that the idea for the novel was conceived while the author performed in Wilkie Collins'' play The Frozen Deep. One scene notes that it took four men ablaze with gorgeous decoration to prepare chocolate for a character who later tosses a coin to a father whose son was killed by his carriage. Divided into three sections titled Recalled to Life, the Golden Thread and the Track of a Storm, one scene sees Defarge read a letter which proves the royal heritage of Charles Darnay. FTP, the line it was the best of times, it was the worst of times opens what work by Charles Dickens?\n'),
(36, 'This man wrote an eight-part "Choric Song" in a poem describing the "languid air" in a land "in which it seemed always afternoon." This poet of "The Lotos-Eaters" described the title objects rising "from the depth of some divine despair" in his "Tears, Ideal Tears" and wrote "after many a summer dies a swan" in another poem. This poet of "Tithonus" and "Locksley Hall" wrote a poem whose speaker wishes to "see his pilot face to face" and a suicide ride by "the six hundred." He wrote about a man who desires "to strive, to seek, to find, but not to yield." For 10 points, name this poet of "The Charge of the Light Brigade" and "Ulysses."\n'),
(37, 'The protagonist of this play attributes Glesne''s deer-hunting feats to himself, and tells a story about trapping the Devil in a nut to explain why he and the blacksmith Aslak don''t like each other. The protagonist impregnates a girl in a green dress merely by desiring to marry her, and encounters the Byg in Act three. In this play''s final act, a button-moulder comes to collect and melt down the soul of this play''s title character, who tries to seduce Anitra in Morocco. The title character reunites with Solveig before returning home before to say farwell to his dying mother, se. For 10 points, name this verse drama by Henrik Ibsen featuring a scene in the hall of the Mountain King, which inspired a suite by Grieg.\n'),
(38, 'In this novel Herbert falls in love with the figurehead of a ship at a Maritime Museum, and impales himself while trying to make love to it. The main character helps Jan Bronski steal a necklace from a jewelry store with one of his special skills. In one scene from this novel, the protagonist''s mother witnesses eels being pulled from the head of a dead horse and dies after confining herself to a diet of fish. The protagonist of this novel is accused of killing Sister Dorothea. The protagonist of this novel has a scream that can shatter glass and decides to stop growing at the age of three. The first novel of the Danzig Trilogy, for 10 points, identify this novel about Oskar Matzerath, written by Gunter Grass.\n'),
(39, 'In one play by this author, the house belonging to the central characters is finally paid off just days before the funeral of the title character, who dies in an automobile crash. This author fictionalized his real-life marriage to Marilyn Monroe in After the Fall and wrote a play in which Uncle Ben strikes it rich in Alaska while Happy and Biff are embittered about their father''s insistence on living the American Dream. For 10 points, identify this American playwright who wrote about Willy Loman in Death of a Salesman.\n'),
(40, 'As a child, this character reads his uncle the column That Body of Yours every Sunday. He sleeps with a cutlass and buys a puppy named Tarzan to protect himself while waiting for Mr. Maclean to finish building a shelter in the Green Vale, which is ultimately burnt down by sugarcane farmers. His father drowns after diving into a pool in a misguided attempt to save this character, who is actually hiding under a bed to avoid punishment for losing a calf. After his son Anand abandons him, he begins to work as a reporter for The Sentinel in Port of Spain. This character works as a sign painter, which brings him to Hanuman House, where he marries Shama by the Tulsi family. For 10 points, name this six-fingered character who struggles to get a house in a novel by V. S. Naipaul.\n'),
(41, 'In this author''s first novel, Eugene Dawn is driven to insanity by his work on the Vietnam Project. In his next novel, Magda, the daughter of a sheep farmer, clashes with her father for taking a black mistress. In addition to Dusklands and In the Heart of the Country, he wrote a work in which Susan Barton meets Friday and Cruso, Foe. He is better known for a novel about Melanie''s affair with Professor David Lurie, which leads to the title condition, and another about the titular hare-lipped gardener, who escapes from a retraining camp hospital and returns to Cape Town. For 10 points, name this South African author of Disgrace and The Life and Times of Michael K.\n'),
(42, 'In an autobiographical novel, this author recalls working at an optical shop, where Olin manipulates him into boxing his coworker, Harrison. One of this authors characters carries a drunken woman to her room, but accidentally smothers her to avoid being noticed by her blind mother. That character is (*) executed for killing Mary Dalton and his girlfriend Bessie. For 10 points, name this African-American author of Black Boy who created Bigger Thomas in Native Son.\n'),
(43, 'One of this book''s characters purchases the freedom of the son of Euricius after having obtained permission to go to Antium because the royal infant died. Two of its characters are imprisoned in a location called the Putrid Pits after having been put into the Mamertine Prison. Its protagonist hires Croton to rescue a different character after listening to a giant (*) Christian named Urban discuss a meeting at Ostranium. Eunice has her vein slit like her master does, who had fallen prey to Tigellinus''s schemes. Although Marcus Vinicius is able to come to terms with Ligia''s death and meet her in heaven, Ursus saves her while in the Coliseum. Closing with Petronius''s death, for 10 points, name this novel set during the reign of Nero by Henryk Sienkiewicz. [Ike]\n'),
(44, 'One character in this play remembers entertaining strangers at a hotel called the Tarantula Arms. One of its plot points centers on the loss of the family estate of Belle Reve. One of its characters is called a survivor of the Stone Age after throwing a radio out a window when it interrupts his poker game with Mitch. A central character of this play declares I have always depended on the kindness of strangers after moving to the Elysian Fields with Stella and Stanley Kowalski. For 10 points, name this Tennessee Williams play about Blanche Dubois.\n'),
(45, 'A play by this author ends with the protagonist''s wife Sarah urging him to "blow on the coal of the heart." In a poem by this author, the speaker describes darkness rising over Ecbatan, Kermanshah, Baghdad, and Palmyra, and imagines lying "face downward in the sun" and feeling "how swift how secretly / the shadow of the night comes on." Another of this author''s poems recommends that a work of art be "wordless as the flight of birds" and "palpable and mute / as a globed fruit." This author wrote a play in which Nickles and Mr. Zuss put on the masks of Satan and God and watch the title character react to calamities originally visited upon Job. For 10 points, name this author of "You, Andrew Marvell" and J. B., an American poet who wrote "a poem should not mean but be" in "Ars Poetica."\n'),
(46, 'Characters in this novel compete in unusual games like Riemann Surface Tennis and Obstacle Golf, and two characters cross the Atlantic in the Red Rocket. It opens with a description of the Bokanovsky process, and one character is threatened with exile to Iceland by [*] Mustapha Mond, an Alpha Double-Plus. The protagonist''s mother is seduced by Pop, who offers her Mescal to replace Soma, and that protagonist hangs himself at the end of the novel, in the year 632 After Ford. For 10 points, name this dystopian novel about Bernard Marx and John the Savage, named for a line from The Tempest and written by Aldous Huxley.\n'),
(47, 'He''s not Thomas Pynchon, but in one story by this author, a character reads psalms over a young woman''s corpse until the titular demon frightens him to death. In addition to Viy, he also wrote a collection of stories narrated by Rudy Panko, Evenings on a Farm Near Dikanka. In one work, Ivan Yakovlevich searches for a lost appendage, until he wakes up thirteen days with it reattached to his face, and in another, Akaki Akakievich saves up for the title article of clothing, only to have it taken violently from him. For 10 points, name this Ukrainian author of The Nose, and The Overcoat best known for Dead Souls.\n'),
(48, 'In this novel, Roth''s fall to his death causes Red Valsen to refuse to continue climbing Mount Anoka. Another character is humiliated when he is forced to pick up a discarded cigarette from the floor by General Cummings. That character, Robert Hearn, is killed after unwittingly walking into an enemy trap when Sam Croft lies about Martinez'' scouting report to regain command of the platoon on Anopopei. For 10 points, name this novel about an invasion of a fictional Pacific island, written by Norman Mailer.\n'),
(49, 'His first publication was a collection of 36 love poems entitled Chamber Music. Stephen Hero was a posthumous publication that contained large portions of another of his works, while Humphrey Chimpdon appears in another work, Finnegan''s Wake. "Eveline", "Araby", "The Dead" and twelve other stories appear in one of his works depicting the middle class life of residents of the title city, while another work about Leopold Bloom contained allusions to a work by Homer. For 10 points, identify this Irish author of A Portrait of the Artist as a Young Man, Dubliners, and Ulysses.\n'),
(50, 'The tailor Mustafa in this story is blindfolded and led by a slave girl to her owner''s house, where he was to sew back together the four pieces of a corpse. A slave conceals the murder and suggests that Cassim was ill. One antagonist finds the house of Cassim''s brother and marks it with a white X so he could come back later to murder him, but the slave Morgiana foils his plan by adding identical marks on all neighboring houses. Morgiana later kills 38 of the title characters as well as their captain with boiling oil. For 10 points, name this story about a cave full of treasure which is opened by saying Open, sesame, a story told by Scheherezade in One Thousand and One Nights.\n'),
(51, 'He wrote a poem about lovers of the title Sphinx, while another of his poems includes a part about the Man of Sorrows, and was posthumously entitled De Profundis. He created Lady Erlynne, who is secretly the mother of a woman who is tempted to run away with Lord Darlington, and in one novel the protagonist is called Prince Charming by Sybil Vane, and that man kills the painter Basil Hallward. For 10 points, name this author of Lady Windemere''s Fan and The Picture of Dorian Gray.\n'),
(52, 'This work''s author asserted that it was written for a generation which knew nothing or next to nothing of war, and hardly dreamed of it. The narrator comforts a character with a poem beginning What endless melodies were poured / As sad as earth, as sweet as heaven, in its final section, The Long Path. Earlier, the protagonist laments the sad state of civilization due to those who call Norridge Norwich and Cincinnati Cincinnatah. The author calls facts the brute beasts of the intellectual domain and claims that all practical wisdom is an extension of 2 + 2 = 4. Beginning with the line I was going to say, when I was interrupted, many of this work''s sections are directed to the divinity student, the schoolmistress, and the landlady, other members of the boarding-house. Serially printed in the Atlantic Monthly, and subtitled Every man his own Boswell, for 10 points, name this collection of essays by Oliver Wendell Holmes Sr.\n'),
(53, 'At the end of this novel, the protagonist''s daughter, Berthe, must support herself by working in a cotton factory. In this novel, a man named Hippolite has his leg amputated after a botched operation. The protagonist of this novel drinks arsenic in order to avoid the shame of her husband discovering her (*) affairs with Leon and Rodolphe. This novel focuses on a woman bored with her marriage to a country doctor named Charles. For 10 points, name this novel about the adulteress Emma, written by Gustave Flaubert.\n'),
(54, 'This man warned against both communism and fascism in a work in which he also drew connections between collectivism and religious fundamentalism, "A Tentative Outline of American Values." In another work, this man adapted Tonnies'' Geminschaft/Gesellschaft axis into a method of describing choices, which he called "pattern variables." In a more famous work, he described a tool for conducting sociology which could be applied to any level of society, the AGIL Paradigm. This author ofToward a General Theory of Action, integrated Pareto and Weber in his first work, and founded structural functionalism. For 10 points, name this author ofThe Social SystemandThe Structure of Social Action.\n'),
(55, 'Andrew Marvell used one of their two chief Roman models for his poem about Cromwell''s return from Ireland. A comic one by Thomas Gray ends "Nor all that glisters, gold," and tells of Selima''s death in a tub of goldfish. Wordsworth''s most famous notes "Our birth is but a sleep and a forgetting" and shows "Intimations of Immorality." Another Romantic one ends "Fled is that musicDo I wake or sleep?", and another declares "Beauty is truth, truth beauty." For 10 points, name this lyric form that Keats used to discuss a nightingale and a Grecian Urn.\n'),
(56, 'One play by this author sees a character dress up as an abbot''s attendant only to be mistaken for Peter Damian. He also wrote a play in which a child drowns in a fountain and a boy shoots himself. That play begins at a rehearsal which is swiftly interrupted, to the (*) Manager''s consternation, by the title figures, of whom only Madame Pace is named. For 10 points, name this Fascist-supporting Italian author of Enrico IV and Six Characters in Search of an Author.\n'),
(57, 'In this play''s first interlude the elderly money-lender Punchinello has to bribe a group of archers to not arrest him for serenading a woman, while earlier in the first act the protagonist chases a servant with a stick for criticizing his decision to betroth his daughter to Thomas Diafoirus. In this play''s third act the diagnosis of Fleurant and Mr. Purgon is contradicted by the maid Toinette while she is disguised pretending to be a famous doctor. The title character of this play discovers the insincerity of his wife Beline when his brother Beralde convinces him to play dead and he ultimately allows his daughter Angelique to marry Cleante. For 10 points, name this Moliere play about Argan who is constantly concerned with his health.\n'),
(58, 'An eating competition with a woman known as The Elephant occurs in this novel, which also details a massacre of banana-farm workers. It ends with one character finally deciphering a message written by the gypsy Melquades, who earlier introduces another character to ice. During his military conquests, that character fathers seventeen children with the name (*) Aureliano. This novel sees rsula live to a supernatural age, and with her husband Jos Arcadio Buenda she establishes the town of Macondo. For 10 points, name this novel by Gabriel Garca Mrquez.\n'),
(59, 'His 1989 Jefferson Lecture in the Humanities was titled The Fateful Rift: The San Andreas Fault in the Modern Mind. He constructed a semiotic analysis of the way Hellen Keller learned the word water in his essay The Delta Factor, which appears in his collection The Message in the Bottle. His other nonfiction includes Signposts from a Strange Land and a parody of self-help books, Lost in the Cosmos. Williston Barret falls in love with Kitty Vaught in his novel The Last Gentleman, and in his last novel, Dr. Tom More encounters a curious flatness of tone in Feliciana, where Dr. Comeaux is heavily dosing patients with sodium. He also wrote a novel about the Kierkegaardian quest of a New Orleans stockbroker more interested in books and film than the routine of his life. For 10 points, name this American author of The Thanatos Syndrome who wrote about Binx Bolling in The Moviegoer.\n'),
(60, 'One character in this novel carries on a running affair with Catherine until Catherine is beaten by Clementine, the wife of Zacharias, who serves as the cook for this novel''s title character. A former assistant to this novel''s titular protagonist, Jean-Martin Le Guen, appears in a later novel by the same author, Le roi miracule. At the end of this novel, it is discovered that the work camp that was intended to instruct young Tala women in the virtues of monogamy has actually been run as a brothel, complete with rampant syphilis. The title village of this novel becomes deserted following the imposition of labor gangs by Vidal, and Denis, the boy from whose viewpoing this novel is told, gives up hope of ever hearing from the title priest. For ten points, identify this novel whose title figure is the Catholic missionary Father Drumont, who preaches the gospel to residents of the title village, the best-known novel of Cameroonian author Mongo Beti.\n'),
(61, 'One character with this surname is has a vision of the Devil, who mocks him for asserting that all men will unite to take from life all it can give. Another character with this surname studies with Father Zossima. One tells the story of The Grand Inquisitor, while another member of this family desperately pursues Grushenka before being falsely convicted for Smerdyakov''s murder of Fyodor. For 10 points, Aloysha, Dmitri, and Ivan are all members of what family, which appears in a namesake novel by Fyodor Dostoevsky?\n'),
(62, 'This author declared "hence vain deluding joys" in a poem hailing the goddess Melancholy. This author of the companion poems "L''Allegro" and "Il Penseroso" wrote "Who kills a man kills a creature, God''s image; but he who destroys a good book...kills the image of God" in an essay arguing in favor of freedom of the (*) press. This author wrote an epic poem beginning "Of man''s first disobedience, and the fruit / of that forbidden tree," which describes a meeting of devils like Beelzebub in Pandemonium where Satan resolves to tempt mankind. For 10 points, name this British author of Areopagitica and Paradise Lost.\n'),
(63, 'In one play by this author, Hugo Barine kills Hoederer (HOY-dur-er), but is unaware that the Party wants to create a martyr. This author of Dirty Hands wrote about the sweetish sickness that afflicts Antoine Roquentin in his novel (*) Nausea. His play about the interactions of Ines, Garcin, and Estelle inspired the saying "Hell is other people." For 10 points, name this author of No Exit and other French existentialist works.\n'),
(64, 'In one novel by this author, the fraught marriage of Bonnie Dee Peacock to Daniel is played for comedic effect. A short story by this author describes Phoenix Jackson''s long walk to town to get medicine for her grandson. This author of the novel The Ponder Heart included the story A Worn Path in her book A Curtain of Green. Troy Flavin marries Dabney Fairchild in the title event of her best-known novel, Delta Wedding. FTP who is this Southern author of the short stories Petrified Man and Why I Live at the P.O.?\n'),
(65, 'One passage in this work exhorts the reader to Drink! For you know not whence you came, nor why. An extended passage near the end of this work describes loquacious vessels of clay, one of whom wonders Who is the potterand who the pot? An oft-quoted verse in this poem warns that The bird is on the wing. Famously translated by Edward Fitzgerald, this work describes A Book of verses underneath the bough / A jug of wine, a loaf of bread - and thou. For 10 points, name this work of 101 quatrains, written by the Farsi poet Omar Khayyam.\n'),
(66, 'One of this writer''s stories follows Annemarie Johansen as she helps her friend Ellen escape from Nazi-occupied Denmark. A sequel to this author''s most well-known book follows the weaver Kira, and that book ends with Jonah and Gabe fleeing the dystopian society they live in. For 10 points, identify this Newbery award winning author who wrote Number the Stars, Gathering Blue, and The Giver.\n'),
(67, 'One of this author''s short stories begins with an eccentric councillor building a house by first erecting the walls and then ordering workmen to smash out the door and windows. In that story by this author, the narrator learns that Krespel''s daughter Antonia has a defect in her chest causing her to die from her beautiful singing. In another short story by this author, a student cries "circle of fire! Spin around" and attempts to kill his fiancee Clara after looking at her through glasses bought from the sinister Coppelius. Freud''s essay "The Uncanny" analyzes this author''s story about Nathaniel, who falls in love with Professor Spalanzani''s daughter Olympia, but discovers that she is a mechanical doll. For 10 points, name this German author of Gothic short stories such as "The Sandman," which inspired Jacques Offenbach to write an opera about his "tales."\n'),
(68, 'This character uses a magic hair-ball he found in the stomach of an ox to prophesy that another characters father is surrounded by a black angel and a white angel. Another character pretends to be Sarah Williams of Hookerville to gather information about this man after he is injured from a failed prank in which someone put a rattlesnake skin in his bed while staying on Jacksons Island. The novels protagonist goes to the farm of Sally Phelps to search for this character after he is betrayed by two con men who claim to be a duke and the dauphin. This character learns Miss Watsons will freed him months earlier after Tom Sawyers escape plan goes awry. For 10 points, name this slave who travels with Huck Finn in a novel by Mark Twain.\n'),
(69, 'In a footnote to this work, the author claims that Mickiewiczs depiction of the same event as this work, while beautiful, was inaccurate. This poem opens with a man standing on the shore imagining a time when all flags will visit us/ and we will celebrate in freedom, after thinking that Nature intends for him to carve a window. This work contains a famous passage expressing the poets love for a city possessed of an Admiralty needle, and this poems protagonist is alleged to have the name he does because the poet is comfortable with it, a reference to that poets earlier work. The protagonist of this work sits on a marble sentry lion looking at his lovers house instead of the title character behind him. After the death of his lover Parasha in a flood, this poems protagonist goes mad and wanders the streets before confronting the title figure. For ten points, identify this poem in which Yevgeniy imagines the title equestrian statue of Peter the Great chasing him through the streets of St. Petersburg, a poem by Alexander Pushkin.\n'),
(70, 'In one of this author''s works, the speaker asserts that "one must be for ever drunken: that is the sole question of importance." Another of his works sees tje speaker attack the title character for having "no coloured glasses." In addition to "Intoxication" and "The Glass-Vendor," he described how "Languorous Asia and burning Africa, / A whole world, distant, absent, almost exist" in the title object of "The Head of Hair." The title character, a "captive king," is mocked because its "giant wings keep them from walking" in his "The Albatross." He opened another work asserting "folly and error...possess our spirits," after which he compares himself to the "hypocrite reader." For 10 points, name this man who wrote the Prose Poems, the French author of The Flowers of Evil?\n'),
(71, 'This author of the novels Lamiel and Lucien Leuwen wrote about Clelia Conti, who helps Gina Pietranera plan the escape of her nephew from the Farnese Tower, in a novel about Fabrizio del Dongo. The protagonist of another of his novels studies under Abbe Pirard at the Bescanon seminary before a letter by Madame de Renal ruins his chance to marry Mathilde de la Mole. For 10 points, name this author of The Charterhouse of Parma who wrote about Julien Sorel in The Red and the Black.\n'),
(72, 'The protagonist of one novel by this author is put off by the proclivity of Russians to share food with their worm-ridden dogs and moves to the residence of an Indian man he labels Mr. Nonentity. In another novel, the protagonist breaks a leaf off a cabbage to find another universe after the stars assuage his anger and prevent him from destroying Earth. In that novel, the protagonist has a relationship with the Dark Lady and his black colleague Valeska, focuses on his dead wife Hymie''s diseased (*) ovaries, and works for the Cosmodemonic Telegraph Company. Another novel features Van Norden and Carl, the friends of a narrator who sings to Tania and promises a kick in the pants of God. For 10 points, identify this lover of Anais Nin, who drew on his expatriate experiences to write the obscene Tropic of Cancer.\n'),
(73, 'The Canadian rock band by this name has released such albums as Take A Deep Breath, Young Wild and Free, and Love Machine and had a 1986 Top Ten single with Can''t Wait For the Night. The song by this name is the first track on Queen''s Sheer Heart Attack. The novel by this name concerns Fred Hale, who returns to town to hand out cards for a newspaper competition and is murdered by the teenage gang member Pinkie Brown, who abuses the title substance. The novel was adapted into a 1947 film starring Richard Attenborough; this was released in the US as Young Scarface. FTP, identify the shared name of, most notably, a novel by Graham Greene.\n');
INSERT INTO `questions` (`qid`, `question`) VALUES
(74, 'This author noted some view "out sable race with scornful eye / Their color is a diabolic die," when showing "my [?] Pagan Land." Another work asks the title figure, "Does not your soul possess the sacred flame?" when he is "beneath the myrtle shade" before "snatch[ing] a laurel from thine honour''d head." Besides "To Maecenas," she wrote "The refluent surges beat the sounding shore / or thick as leaves in Autumn''s Golden rain," before "One century scarce perform''d its destined round / When Gallic powers Columbia''s fury found." She began that work with "Celestial choir! enthron''d in realms of light." For ten points, name this poet of Poems on Various Subjects, and To His Excellency George Washington, a founder of African-American literature.\n'),
(75, 'In one of his short stories, the protagonist Sammy gives the unflattering nickname of "Big Tall Gooney" to one character. In that story, Sammy is quits his job after Lengel threw three girls in bathing suits out of the title grocery store, "A&P." This man also wrote a series of novels about a former basketball star who has an unhappy marriage to Janice, Harry Angstrom. For 10 points, name this author of novels such as Rabbit Redux and Rabbit Run.\n'),
(76, 'This author wrote about characters encountering the bland women Kate Lancaster and Helen Denis while on vacation in the novel Deephaven. This author wrote about Joseph Laneway''s return to Abby Harran in the titular town in the story A Native of Winby, and described Nan Thatcher''s tutelage under Dr. Leslie in A Country Doctor. She wrote a story about Sylvia''s reluctance to reveal the location of the title creature, and penned another novel in which Captain Littlepage bores the narrator, while she visits Mrs. Almira Todd in Dunnet Landing, Maine. For 10 points, name this author who wrote A White Heron and The Country of the Pointed Firs.\n'),
(77, 'This essay contrasts the Man of Science, who seeks truth as a remote and unknown benefactor, with the Poet, who sees it as our visible friend and hourly companion, though the latter is ready to transfigure science and make it familiarized to men. It also dismisses a Samuel Johnson poem by claiming Why take pains to prove that an ape is not a Newton, when it is self-evident he is not a man, and claims there are only five good lines in a Thomas Gray sonnet when it makes its argument for the merit of prosaic rhythm. It pronounces poetry to be (*) the spontaneous overflow of powerful feelings, which begin in emotion recollected in tranquility, and suggests that poets should look more to common life and the language really used by men. For 10 points, name this manifesto of British Romanticism that introduces a poetry collection including Goody Blake and Harry Gill, The Idiot Boy, and The Rime of the Ancient Mariner, written by William Wordsworth\n'),
(78, '[MB/JM]One king of this name and number was killed by Sir Robert Graham after being discovered hiding under his tennis court because he had ordered its drain blocked up the previous day. As a youth, that king of this name and number hid at Dirleton Castle before being captured by pirates and delivered to Edward IV. Another king of this name and number expelled the Moors from the Balearic Islands in 1232, while a different king who would later be called by this name and number was the target of the Raid of Ruthven, which put his country temporarily under the control of the Gowrie Regime. Also naming a man who took part in the crusade of 1269 but turned around after stormy weather, a British king of this name and number was almost made to sign the Great Contract by Robert Cecil and authored books like the ? witch hunting guide,Daemonologie. Identifying "the most renowned of the medieval kings of Aragon" known as The Conqueror, for 10 points, give this common name and number that also identifies a king targeted in the Gunpowder Plot, the first Stewart King of England.\n'),
(79, 'This author was accused of portraying Americans as "Time-reading, Republican Voters" in a book about Jay Pignatelli. Another work sees one of the title characters meeting the sympathizer Genevieve and a man chucking two grenades at his hated sergeant. The other title character in that novel by this author is deserted by Mabe and promoted to corporal. Beyond Chosen Country and Three Soldiers, another of his works sees Bud Korpening committing suicide, as well as John Oglethorpe marrying Ellen Thatcher. Another novel sees Lloyd Wright designing buildings, Margo Dowling supporting communists and Charlie Anderson crashing cars. For ten points, name the author of Manhattan Transfer and The Big Money, the latter of which forms the U.S.A. Trilogy.\n'),
(80, 'A girl is exposed as a man in drag at the end of one of his plays, which sees Sir Dauphine Eugenie tolerate his uncle Morose''s hatred of noise. In addition to Epicoene, one of his plays sees Subtle and Face dupe Pertinax Surly and Sir Epicure Mammon, and another features a man named Sir Politic Would-Be. His best-known poem begins Drink to me only with thine eyes, and is titled To Celia. For 10 points, name this playwright of The Alchemist and Volpone.\n'),
(81, 'Three of the sections of this work are followed by epigrammatic workpoints, including a series of character-squeezes describing Teresa di Petromonti as a farded Berenice and Fuad El Said as a black moon-pearl. Its third section climaxes with a confrontation between Narouz and Nessim, while the climax of its first section is the supposed death of Capodistria during a duck-shoot on Lake Mareotis. The title character of its first section is the subject of Arnauti''s novel Moeurs and is a lover of the narrator of much of this work, L.G. Darley, like the title character of its last section, Clea. For 10 points, name this series also including the novels Justine, Balthasar, and Mountolive, a novel cycle by Lawrence Durrell taking place in the title city.\n'),
(82, 'Major commentaries on this work were written by "Odd Tablet" and Zhiyanzhai, and it first became known to the public after an edition was published by Cheng Weiyuan and Gao E. This novel, which was notably translated into English by David Hawkes, features a frame story in which Zhen Shi-yin reads the lines "truth becomes fiction when the fiction''s true / Real becomes not-real when the unreal''s real" during a reverie which begins with the fairy Disenchantment deciding to reincarnate the Crimson Pearl Flower. This novel''s main plot describes the love between Lin Dai-yu and Bao-yu during the downfall of the Jia family, and the lives of the "Twelve Beauties of Jinling." For 10 points, name this eighteenth century classic Chinese novel written by Cao Xuequin.\n'),
(83, 'This man''s collection Why Did You Leave the Horse Alone is considered his most autobiographical writing, a departure from book-length poems like Another Year and That is Her Image and This is The Lover''s Suicide. His best-known prose poetry describes being killed in a flash, the comforts of cigarettes and coffee and the sounds of war planes. One poem by this man was published in translation in Ma''ariv in 1988, giving this man overnight celebrity thanks to Shefi Gaabi mistranslating expressions like from the sea to the Jordan River. Those works are Memory for Forgetfulness about Lebanon in 1982 and the Those Who Pass Between Fleeting Words. With Arabic poetry collections like Birds are Dying in Galilee and Writing in the Light of the Gun, FTP, identify this man who wrote record!/I am an Arab in his Identity Card, a Palestinian poet.\n'),
(84, 'This work''s author recalls its creation by citing the influence of Ode to the Rosemary by Henry Kirke White and two similarly themed poems of Robert Blair and Bishop Porteus. One entity in this poem treads upon the sluggish clod. It speaks of complaining brooks, vales / stretching in pensive quietness and hills rock-ribbed and ancient as the sun. This work notes the gay will laugh, the solemn brood of care / will plod on and each one as before will chase his favorite (*) phantom. Urging its addressee to be sustained and smoothed by an unfaultering trust, its author was seventeen when he submitted it to the North American Review to get it published. Also mentioning the Barcan wilderness, it urges for its subject to go like the quarry halls of night, when he joins the innumerable caravan. For 10 points, name this William Cullen Bryant poem that is a meditation on death. [Ike]\n'),
(85, 'The protagonist of this novel is allowed to keep some savings for a hat in the winter season and is taken to Garfield Park before being given 20 dollars after a huge lunch. This novel ends with a man using a gas jet to commit suicide in a [?] flophouse, and that character used to frequently stay in hotels looking at rich people. The protagonist uses the last name Wheeler while married, and assumes a pensive pose while on a rocking chair frequently. Bob Ames and the Vances help the protagonist join the stage, and that protagonist lives with Lola and is the subject of interest of Charles Drouet. For ten points, money is stolen from a salon by George Hurstwood in this work focusing on Caroline Meeber written by Theodore Dreiser.\n'),
(86, 'In one work, this poet asserted that rank and riches vanish and asked you toil and toil  what for? and which was real  the butterfly or the man? He described how his shadow tangles and breaks in the dance he weaves in a poem about raising his cup to the bright moon. A third poem by this author of (*) Chuang Tzu and the Butterfly opens at a time when the speaker''s hair was still cut straight across her forehead and tells of how at sixteen, the poem''s addressee went into far Ku-to-en. A translation of that poem appeared in Ezra Pound''s Cathay. For 10 points, name this author of Drinking Alone by Moonlight and The River Merchant''s Wife, a Tang Dynasty colleague of Du Fu.\n'),
(87, 'One character in this work notes that he can''t trust anyone who hasn''t either given birth or been in an orgy, justifying his distrust of Pastor Rosenquist. Another part of this work details the history of the privateer ship Fortuna II, and another sees several characters watch the marionette play Revenge of the Truth the night before Nino and Prince Pozentiani duel. Other sections see Baron von Brackel reminisce about how he thought he''d seduced a stranger before realizing in the morning she was a prostitute; soprano Pellegrina Leoni (*) lose her voice and switch identities; and Calypso and Miss Malin exchange tales with a Cardinal who finally reveals himself to be the actor Kasparson just before they drown in a freak deluge. For 10 points, The Monkey, The Dreamers, and The Supper at Elsinore are among the novellas included in what collection by Isak Dinesen that, despite its name, takes place in the nineteenth century?\n'),
(88, 'Show off your knowledge about some bitchiness between 18th-century English writers for 10 points each. Joseph Andrews and Shamela were parodies written to mock stylistic flaws in this author''s incredibly long epistolary novel Pamela.\n'),
(89, 'One man from this country wrote an essay arguing that writers like Leon Bloy and Lord Dunsany are seen as connected only because they both influenced the essays title author, and that every writer creates his own precursors. That essay in Kafka and his Precursors. Another writer from this country praised tristes and vidalitas, peasant songs from this country, but criticized the culture they came from, represented by the title figure, for retarding this countrys progress. That work is Facundo. A critic of that work and its author Sarmiento wrote a poem whose title character leaves his post as a frontier soldier after trouble with the law and joins Sergeant Cruz to pursue the gaucho way of life; that work is Martin Fierro. For 10 points, name this home of Jose Hernandez and Jorge Luis Borges.\n'),
(90, 'This author wrote a play in which the queen Atossa and the ghost of Darius react to news of a military defeat; that play is the only classical tragedy on a contemporary, rather than mythical, subject. This author of The Suppliants and The Persians also wrote about a man who is pursued to Athens to stand trial for murdering Clytemnestra, which happens in The Libation-Bearers. For 10 points, name this author of The Eumenides (yoo-MEN-id-eez) and Agamemnon, part of his Oresteia.\n'),
(91, 'This person was paired with love in the title of a work by Hannah Arendt. Near the end of his life, he looked back on his writing in the book Reconsiderations. An opponent of both the Donatists and Pelagians, this writer responded to Alaric''s sack of Rome by writing a book that contrasted Rome with the titular metaphorical Jerusalem, The City of God. He described his upbringing by Monica and conversion by Ambrose of Milan in another work. For 10 points, name this North African theologian who died in 430 CE after writing his Confessions.\n'),
(92, 'In one scene in this novel, the protagonist''s son doesn''t get a chance to eat any of a castle-shaped jelly dessert. The protagonist of this novel contemplates death while looking at a painting called Death of the Just Man in a library. In the final scene of this novel, the embalmed corpse of a dog is thrown out of a window because of Concetta''s anger at Tancredi, who marries Angelica instead of her. The protagonist is annoyed at the newly acquired wealth of Don Calogero, who fought under Garibaldi. The protagonist is a Sicilian nobleman, Don Fabrizio, whose coat of arms depicts the title animal. For 10 points, name this novel by Giuseppe Tomasi di Lampedusa.\n'),
(93, 'At one point, this work diverges from the plot to spend an entire chapter explaining the meaning of the sentence, "This will kill that," with "this" referring to the printing press. The antagonist of this work arranges with Jehan to view a love scene between two characters before stabbing the male and blaming it on the female. That antagonist, Claude (*) Frollo, is pushed off the title edifice by another character who witnesses him celebrating Esmeralda''s death. For 10 points, name this work by Victor Hugo about Quasimodo, a bell-ringer in Paris''s most famous cathedral.\n'),
(94, 'This work puns on the word pensive by using its original Latin meaning of hanging. This work''s images include the genii of the stream, and it uses the phrase with many an ardent wish. It notes that purple  betrayed a golden gleam" and its central subject is served by Tom and Susan. Declaring "a favorite has no friend, Malignant fate, [who] sat by and smiled / [as] the slippery verge her feet guiled, This poem begins Twas (*) on a lofty vase''s side, / where China''s gayest art had died, and it is the source of the phrase not all that glisters is gold. For 10 points, name this poem that describes the pensive Selima reclined / gazed on the lake below, which describes what happens when a kitty thinks it''s a good idea to stick its head in a tub of goldfishes, written by Thomas Gray. [Ike]\n'),
(95, 'At one point in this work, the title character reveals his hope of spending his life alone, passing time drinking good coffee and reading the works of Homer.  The protagonist works for a young prince after failing to enter the army.  This occurs after he resigns the position secured for him by Wilhelm.  After returning to Walheim, Albert''s wife asks the protagonist to read Ossian to her.  In a section entitled "The Editor to the Reader," a neighbor reports the flash of two pistols brought to the protagonist by his servant.  Ending with the title character''s suicide due to his obsession with Charlotte, FTP name this Goethe novel.\n'),
(96, 'This artist included Reincarnation of a Lovebird in an album featuring narration by Jean Shepherd who describes a man who tried to please most people . . . but nobody liked until he was dead in The Clown. This artist ran a group called The Jazz Workshop and often collaborated with drummer Dannie Richmond and pianist Jaki Byard. He had his psychotherapist Edmund Pollock to write the liner notes for his six-part suite The Black Saint and the Sinner Lady. This musician made an album titled after his name Ah Um that featured the track Fables of Faubus and a piece later called Theme for Lester Young. The instruments imitate police whistles and car horns in his reimagining of a Gershwin classic A Foggy Day found on an album titled for a tone poem about humanity''s evolution into a upright hominid and eventual downfall from pride. For 10 points, name this jazz musician who composed Goodbye Pork Pie Hat and the album Pithecanthropus Erectus who played the bass.\n'),
(97, 'In one of this author''s novels, the protagonist is an eleven-year-old girl who is raped by her father, Cholly. This creator of Pecola Breedlove also wrote a work that details the family history of Milkman Dead the Third. In another novel by this author, Sethe (seth-ee) and Denver live at 124 Bluestone, a house that is haunted by the ghost of a two- year-old who was killed with a handsaw so that she would not have to live in slavery. This author wrote The Bluest Eye and Song of Solomon. For 10 points, name this female African-American author who wrote Beloved.\n'),
(98, 'At one point, these characters climb into barrels aboard a ship bound for England. Later, one of these characters stabs the Player with what turns out to be a fake knife. That stabbing leads to the Tragedians acting out various types of stage death, while these two characters contemplate their (*) impending execution. As one work in which they appear begins, a coin comes up heads 89 times in a row. For 10 points, name these two minor characters in Hamlet, who are both declared dead in the title of a Tom Stoppard play.\n'),
(99, 'One character in this work is a replacement for Poor John macmillan who died of cerebral malaria. In one episode from this novel, Moses prevents an attack on Wright after he whips another road worker, and another character in this novel is the preacher John Goodcountry. One character in this work counters an accusation from Clarke of a lack of interest by muttering Shit on the Lieutenant Governor and has a relationship with the doctor Mary Savage. That character also breaks all of the guns in the town he is responsible for. At the end of this novel, the protagonist''s eldest son drops dead after participating in a funeral ritual, and earlier Oduche tries to kill a sacrificial python. The protagonist of this work is opposed by District Commissioner Winterbottom who jails him for thirty two days, and eventually the Chief Priest of Ulu, named Ezeulu, falls into madness. For 10 points, identify this work depicting Umuaro''s fall into Christian dominance, a work of Chinua Achebe.\n'),
(100, 'This author wrote about a lecture led by Professor Put-Them-All-In-Spirits about humans and apes with hippopotamus majors in their brains, which simplified his earlier satire on the hippocampus debates of Owen and Huxley. One of his title characters works for the Weekly Warwhoop and becomes a labor agitator after befriending John Crossthwaite. That novel by this author is about a tailor and poet who becomes a Chartist, exemplifying this authors doctrine of muscular Christianity. This author also wrote a book in which two fairies named Do-as-you-would-be-done-by and Be-done-by-as-you-did instruct the moral progress of the protagonist. In that book by this author, a chimney-sweep named Tom drowns, and is transformed into one of the title water-bound beings. For 10 points, name this Victorian author of Alton Locke and The Water-Babies.\n');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` char(255) NOT NULL,
  `firstname` varchar(255) NOT NULL,
  `lastname` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `last_qid` int(11) DEFAULT NULL,
  `last_login` timestamp NULL DEFAULT NULL,
  `last_ip` varchar(255) DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Table structure for table `user_history`
--

CREATE TABLE IF NOT EXISTS `user_history` (
  `uid` int(11) NOT NULL,
  `qid` int(11) NOT NULL,
  `position` int(11) NOT NULL,
  UNIQUE KEY `uid` (`uid`,`qid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;




/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
